from enum import Enum


class WirepasErrorCode(str, Enum):
    WERR_ACCESS_NOT_ALLOWED_DATA = "WERR_ACCESS_NOT_ALLOWED_DATA"
    WERR_ACCESS_NOT_ALLOWED_OPERATION = "WERR_ACCESS_NOT_ALLOWED_OPERATION"
    WERR_API_VALIDATION = "WERR_API_VALIDATION"
    WERR_CONTENT_TOO_LARGE = "WERR_CONTENT_TOO_LARGE"
    WERR_DATABASE_ERROR = "WERR_DATABASE_ERROR"
    WERR_DUPLICATE_IDENTIFIER = "WERR_DUPLICATE_IDENTIFIER"
    WERR_FAILED_RESOURCES = "WERR_FAILED_RESOURCES"
    WERR_GENERAL_ERROR = "WERR_GENERAL_ERROR"
    WERR_INVALID_CONTENT = "WERR_INVALID_CONTENT"
    WERR_INVALID_CREDENTIALS = "WERR_INVALID_CREDENTIALS"
    WERR_INVALID_FIELD_VALUE = "WERR_INVALID_FIELD_VALUE"
    WERR_INVALID_HEADERS = "WERR_INVALID_HEADERS"
    WERR_INVALID_IDENTIFIER = "WERR_INVALID_IDENTIFIER"
    WERR_INVALID_PARAMETERS = "WERR_INVALID_PARAMETERS"
    WERR_INVALID_QUERY = "WERR_INVALID_QUERY"
    WERR_INVALID_QUERY_PARAMETERS = "WERR_INVALID_QUERY_PARAMETERS"
    WERR_INVALID_REFERENCE = "WERR_INVALID_REFERENCE"
    WERR_INVALID_STATE = "WERR_INVALID_STATE"
    WERR_MESSAGING_ERROR = "WERR_MESSAGING_ERROR"
    WERR_MISSING_CONTENT = "WERR_MISSING_CONTENT"
    WERR_OPERATION_TIMEOUT = "WERR_OPERATION_TIMEOUT"
    WERR_OVERLAPPING_OPERATION = "WERR_OVERLAPPING_OPERATION"
    WERR_PRECONDITION_ERROR = "WERR_PRECONDITION_ERROR"
    WERR_PRECONDITION_VALIDATION = "WERR_PRECONDITION_VALIDATION"
    WERR_RESOURCE_IN_USE = "WERR_RESOURCE_IN_USE"
    WERR_STATE_CHANGE_NOT_ALLOWED = "WERR_STATE_CHANGE_NOT_ALLOWED"
    WERR_UNKNOWN_FIELD = "WERR_UNKNOWN_FIELD"
    WERR_UNKNOWN_RESOURCE = "WERR_UNKNOWN_RESOURCE"

    def __str__(self) -> str:
        return str(self.value)
